@Library('entapps-shared-library')_
pipeline {
    agent { label 'OIT-ENTAPPS-DEVOPS' }
    environment {
        functionalTesting = "${params.Functional_Testing}"
        vaultpassword = credentials('vaultkey')
        pass = credentials('VNDEVKEY')
        user = credentials('user')
        ota_user = credentials('ota_user')
        ota_pass = credentials('ota_pass')
        oce_user = credentials('oce_user')
        oce_pass = credentials('oce_pass')
        ANSIBLE_FORCE_COLOR = true

    }
    options { skipDefaultCheckout() 
    buildDiscarder(
        logRotator(
            // number of build logs to keep
            numToKeepStr:'5',
            // history to keep in days
            daysToKeepStr: '5',
            // artifacts are kept for days
            artifactDaysToKeepStr: '5',
            // number of builds have their artifacts kept
            artifactNumToKeepStr: '5'
        )
    )
    ansiColor("xterm")
    }
    tools { 


            maven 'mvn 3.6.2'
            jdk 'JDK 8u221'
            //nodejs 'NodeJS10.16.0'
            }

    stages {
        stage('Checkout Repo') {
            steps {
                script
                {
                    cleanWs()
                    sh """ if [ -d "ci-repo" ];then echo "Directory exists";else mkdir ci-repo;fi """
                    sh """ if [ -d "config-repo" ];then echo "Directory exists";else mkdir config-repo;fi """        
                   dir('config-repo')
                    {
                        gitCheckout(
                        branch: "${env.Application_Repo_Branch}",
                        url: "${env.Application_Repo_Url}"
                    )
                    }
                   dir('ci-repo')
                   {

                   gitCheckout(
                        branch: 'master',
                        url: 'https://orahub.oci.oraclecorp.com/oit-entapps-devops/jenkins-pipeline.git'
                    )
                   }


                   
                }
            }
        }
        stage ('Prepare Environment') {
            steps {
                script
                {
                    sh 'mv ci-repo/* config-repo'
                    sh 'rm -rf ci-repo'
                    dir('config-repo')
                    {
             envSet()
             setProperty()
                    }

            }
        }
        }
        stage ('Build') {
            steps {  
                script
                {
                dir('config-repo')
                {
                    if (env.Build_Type == 'Maven')
                    {
                      mavenBuild()
                     }
                     if (env.Build_Type == 'Npm')
                     {
                         npmBuild()
                     }
                    if (env.Build_Type == 'Maven-Npm')
                     {
                         mavennpmbuild()
                     }
                     if (env.Build_Type == 'npmmaven')
                     {
                         npmmaven()
                     }

            }
                }
        }
        }
        stage('Create Tag on the latest commitID') {
            steps
            {
                script
                {
                    createTag()
                }
            }
        }
        stage('Artifactory Upload') {
            steps {
                script
                {
                    env.tagNum = "${params.tag_number}"
                    def appname_repo = sh (script: "echo ${app_name}|cut -d '.' -f 1", returnStdout: true).trim()
                    env.appnameRepo = appname_repo
                    dir('config-repo')
                    {
                uploadArtefact(
                 earPath: "${app_path}",
                 targetFolder: "${artifactory_repo_name}/release/${env.appnameRepo}-${env.tagNum}/"
                ) 

                }
            }
        }
        }
        /*
        stage('ApprovalEmail') {                   
            steps {  
                script { 
                    dir('config-repo')
                    {
                    approvalEmail(
                        recipientEmail: "${receiver_email_id}",
                        senderEmail: "${sender_email_id}"
                    )
    }
                }
}
        }
        */
        stage('Deployment') {
            steps {
                   script {
                       dir('config-repo/ansible')
                       {
                        def repo_url="${env.Application_Repo_Url}"
                        keyName= repo_url.split('/')[3]
                        sh """ echo "${vaultpassword}" > ./.vault_pass.txt """
                        sh """ ansible-vault view ./../key/masterkey.pem --vault-password-file=./.vault_pass.txt > servkey.pem """
                        sh """ chmod 400 servkey.pem """
                        sh """ if [ -f ${app_name} ];then echo "Package already present"; else mv ./../${app_path} . ;fi """
                        sh 'echo "copying files for deployment" '
                        sh """ ansible-playbook -i hosts copytemplate.yml -e 'envtype=${env.environment_type} WeblogicSSLType=${WeblogicSSLType} serverHostUrl=${serverHostUrl} appname=${keyName} deploy_type=APP'  """
                        sh 'echo "Deployment started" --------------------------'
                         if ("${keyName}" == 'recruit-software-dev' || "${keyName}" == 'oit-entapps-devops')
                        {
                        sh """ ansible-playbook -i hosts deploy_main.yml -e 'WeblogicSSLType=${WeblogicSSLType} envtype=${env.environment_type} username=${ota_user} password=${ota_pass} deploymentName=${ApplicationName} deploymentFile=${app_name} serverHostUrl=${serverHostUrl} portnumber=${portnumber} deploymentTarget=${deploymentTarget} wlst_location_home=${wlst_location_home}' """
                        }
                        /*
                        else if ("${keyName}" == 'oce-martech-dev')
                        {
                            sh """ ansible-playbook -i hosts deploy_main.yml -e 'WeblogicSSLType=${WeblogicSSLType} envtype=${env.environment_type} username=${oce_user} password=${oce_pass} deploymentName=${ApplicationName} deploymentFile=${app_name} serverHostUrl=${serverHostUrl} portnumber=${portnumber} deploymentTarget=${deploymentTarget} wlst_location_home=${wlst_location_home}' """
                        }
                        */
                        else
                        {
                          sh """ ansible-playbook -i hosts deploy_main.yml -e 'WeblogicSSLType=${WeblogicSSLType} envtype=${env.environment_type} username=${user} password=${pass} deploymentName=${ApplicationName} deploymentFile=${app_name} serverHostUrl=${serverHostUrl} portnumber=${portnumber} deploymentTarget=${deploymentTarget} wlst_location_home=${wlst_location_home}' """  
                        }

            }
                   }
            }
        }
       
        stage('Functional Testing') {
           when 
                {
                 environment name: 'functionalTesting', value: 'true'
                    }
            steps {
                script
                {
                    dir('config-repo')
                    {
                   println "Proceeding for Functional Testing"
                }
                }
            }
        }
         stage('Email')
        {
            steps
            {
                script
                {
                    dir('config-repo')
                    {
                    emailNotification(
                        recipientEmail: "${receiver_email_id}"
                    )
                }
            }
            }
        }
    }

    post
    {
        success
        {
            cleanWs()
        }
        failure {
            sh """ if [ -f config-repo/ansible/servkey.pem ];then sudo rm -rf config-repo/ansible/servkey.pem;else echo "pem not present";fi """
        }
    }

}
